package http

const (
	Accept             = "Accept"
	AcceptCharset      = "Accept-Charset"
	AcceptEncoding     = "Accept-Encoding"
	AcceptLanguage     = "Accept-Language"
	AcceptRanges       = "Accept-Ranges"
	Age                = "Age"
	Allow              = "Allow"
	Authorization      = "Authorization"
	CacheControl       = "Cache-Control"
	Connection         = "Connection"
	ContentEncoding    = "Content-Encoding"
	ContentLanguage    = "Content-Language"
	ContentLength      = "Content-Length"
	ContentLocation    = "Content-Location"
	ContentType        = "Content-Type"
	ContentMD5         = "Content-MD5"
	ContentRange       = "Content-Range"
	Date               = "Date"
	ETag               = "ETag"
	Expect             = "Expect"
	Expires            = "Expires"
	From               = "From"
	Host               = "Host"
	IfMatch            = "If-Match"
	IfModifiedSince    = "If-Modified-Since"
	IfNoneMatch        = "If-None-Match"
	IfRange            = "If-Range"
	IfUnmodifiedSince  = "If-Unmodified-Since"
	LastModified       = "Last-Modified"
	Location           = "Location"
	MaxForwards        = "Max-Forwards"
	Pragma             = "Pragma"
	ProxyAuthenticate  = "Proxy-Authenticate"
	ProxyAuthorization = "Proxy-Authorization"
	Range              = "Range"
	Referer            = "Referer"
	RetryAfter         = "Retry-After"
	Server             = "Server"
	TE                 = "TE"
	Trailer            = "Trailer"
	TransferEncoding   = "Transfer-Encoding"
	Upgrade            = "Upgrade"
	UserAgent          = "User-Agent"
	Vary               = "Vary"
	Via                = "Via"
	Warning            = "Warning"
	WWWAuthenticate    = "WWW-Authenticate"
)

const (
	XForwardedFor       = "X-Forwarded-For"
	XForwardedHost      = "X-Forwarded-Host"
	XForwardedProto     = "X-Forwarded-Proto"
	XRealIP             = "X-Real-IP"
	XRequestID          = "X-Request-Id"
	XRequestedWith      = "X-Requested-With"
	XFrameOptions       = "X-Frame-Options"
	XContentTypeOptions = "X-Content-Type-Options"
	XXSSProtection      = "X-XSS-Protection"
	XDownloadOptions    = "X-Download-Options"
)
